### ISSUE TITLE
Docs: como eu rodo o projeto?

### ISSUE THREAD

**Issue by danielhe4rt** [stherzada/portfolio#1]
Olá, tudo bem? Gostei bastante do projeto, porém eu sou iniciante e não sei como rodar ele na minha maquina.

Como eu posso fazer pra rodar isso aqui? Existe alguma documentação inicial do projeto? 

Come to brazil!!!

**Comment by Marleyedrg** [comment]
Realmente está faltando documentação nesse projeto.😕
